name: Auto Merge PR

on:
  workflow_run:
    workflows:
      - "PR Check"
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Find PR and enable auto merge
        run: |
          PR_NUMBER=$(gh pr list \
            --state open \
            --json number,headRefOid \
            --jq '.[] | select(.headRefOid=="${{ github.event.workflow_run.head_sha }}") | .number')

          if [ -z "$PR_NUMBER" ]; then
            echo "No PR found"
            exit 0
          fi

          gh pr merge "$PR_NUMBER" \
            --auto \
            --merge

        env:
          GH_TOKEN: ${{ github.token }}
